import plan_B.time_cut
import plan_B.freq_cut

%% Shapes
data = rand(13, 3);
assert(isequal( ...
    size(connect_and_drop(data, "MaxGap", 5, "MinDuration", 3)), ...
    size(data) ...
));
assert(isequal( ...
    size(time_cut(data)), ...
    size(data) ...
));
assert(isequal( ...
    size(freq_cut(data, "SamplingRate", length(data))), ...
    size(data) ...
));

%% Burst error
data = [zeros(1, 10) ones(1, 5) zeros(1, 20) ones(1, 7) zeros(1, 10)].';
burst = [zeros(1, 25) ones(1, 3) zeros(1, 24)].';
assert(isequal( ...
    connect_and_drop(data + burst, "MaxGap", 5, "MinDuration", 5), ...
    data ...
));

%% Small gap
data = [zeros(1, 10) ones(1, 5) zeros(1, 20) ones(1, 7) zeros(1, 10)].';
gap = zeros(size(data));
gap(13) = 1;
gap(30) = 1;
assert(isequal( ...
    connect_and_drop(data - gap, "MaxGap", 5, "MinDuration", 5), ...
    data ...
));

%% Ideal signal
data = [zeros(1, 10) ones(1, 7) zeros(1, 10) ones(1, 7) zeros(1, 10)].';
assert(isequal( ...
    connect_and_drop(data, "MaxGap", 7, "MinDuration", 7), ...
    data ...
));
assert(isequal( ...
    time_cut(data, "SamplingRate", 1, "DurationEstimated", 7), ...
    data ...
));
assert(isequal( ...
    freq_cut(data, "SamplingRate", length(data), "BandWidthEstimated", 7), ...
    data ...
));

%% Negligible noise
data = [zeros(1, 10) ones(1, 7) zeros(1, 10) ones(1, 7) zeros(1, 10)].';
with_noise = data + 0.1 * ones(size(data));
assert(isequal( ...
    time_cut(with_noise, "SamplingRate", 1, "DurationEstimated", 7), ...
    data ...
));
assert(isequal( ...
    freq_cut(with_noise, "SamplingRate", length(data), "BandWidthEstimated", 7), ...
    data ...
));

%% Alternating signal
data = [zeros(1, 10) ones(1, 7) zeros(1, 10) ones(1, 7) zeros(1, 10)].';
n = length(data) / 2;
assert(round(n) == n);
data = data .* reshape([1 -1].' * ones(1, n), [], 1);

assert(isequal( ...
    data .* time_cut(data, "SamplingRate", 1, "DurationEstimated", 7), ...
    data ...
));
assert(isequal( ...
    data .* freq_cut(data, "SamplingRate", length(data), "BandWidthEstimated", 7), ...
    data ...
));
