function reducer = prepare_reducer()
%prepare_reducer - 制备数字滤波器
%
% 输出：
% - reducer：滤波器，用于`reduce_noise`

reducer = designfilt( ...
    'bandpassfir', ...
    'SampleRate', 100, ...
    'StopbandFrequency1', 2, 'StopbandAttenuation1', 13, ...
    'PassbandFrequency1', 3, 'PassbandFrequency2', 8, 'PassbandRipple', 1, ...
    'StopbandFrequency2', 15, 'StopbandAttenuation2', 13, ...
    'DesignMethod', 'equiripple' ...
);

end
